# Generated by Django 5.2.6 on 2025-09-30 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Curso')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('course_type', models.CharField(choices=[('demo', 'Demo'), ('level', 'Por Nivel'), ('custom', 'Personalizado')], default='level', help_text='Demo, Por Nivel o Personalizado.', max_length=20, verbose_name='Tipo de Curso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('tutor', models.ForeignKey(help_text='Tutor dueño y creador de este curso.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created_at'],
            },
        ),
    ]
